# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d7f8477c8af0059ea036a2d518f1e108242793f3dce31c9ea8102b2f44771a607c961bcd3de7a0c31a2630942e1fb57422aadb4894cdabd9f18dcde51571e09a

test:
  secret_key_base: 34f61d531c56d70c25f61e4d1463544f89b00080ba917a7644464ff6d2522d4d7299344581dcb489dcb9f91ba63dd29ecbddcb442832afd7e77f9ad593b639db

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
